export const LOAD_CONTACTS = "LOAD_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
